### ISSUE TITLE
Features I would want:

### ISSUE THREAD

**Issue by ghost** [znepb-cc/zwm#2]
- Functional Desktop
- Recycle Bin
- File Manager
- Right Clicking
- Use of disabled buttons
- Opus Protocol Support
- CC Printing GUI

**Comment by znepb** [comment]
Originally, zwm was just meant to be a test of what I could make. Therefore, most of it is spaghetti code. I am working on a new actual OS (zOS 2) that I've just been touching here and there. It will feature an actual drawing api, and many more things. Keep yer eyes peeled! 👀
